package espl.apps.padosmart.utils

val GENDER_MALE = 0
val GENDER_FEMALE = 1
val GENDER_OTHERS = 2
val REQUEST_FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 34
val END_USER = 1
val SHOP_USER = 2
val NEW_USER = 3
val AUTH_ACCESS_FAILED = 0

