package espl.apps.padosmart.utils

val GENDER_MALE = 0
val GENDER_FEMALE = 1
val GENDER_OTHERS = 2
val REQUEST_FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 34


val END_USER = 1
val SHOP_USER = 2
val SHOP_UNVERIFIED = 4
val SHOP_INIT_LOGIN = 5
val NEW_USER = 3
val AUTH_ACCESS_FAILED = 0

val PAYMENT_TYPE_CASH = 0
val PAYMENT_TYPE_CARD = 1
val PAYMENT_TYPE_MOBILE = 2

val NODE_SHOPS = "shops"
val NODE_ORDERS = "orders"
val NODE_USERS = "users"
val NODE_ACCESS_PERMS = "access_permissions"
val NODE_APP_VERSION = "app"

val SUB_NODE_VERSION = "version"

val QUERY_ARG_CUSTOMER_ID = "customerID"
val QUERY_ARG_SHOP_ID = "shopID"
val QUERY_ARG_ORDER_STATUS = "orderStatus"
val QUERY_ARG_CUSTOMER_ONLINE = "customerOnline"
val QUERY_ARG_SHOP_COUNTER = "shopVisitCount"
val QUERY_ARG_CITY = "city"
val QUERY_ARG_SHOP_STATUS = "shopStatus"
val QUERY_ARG_SHOP_CREATION_DATE = "shopCreationDate"


val ORDER_STATUS_NOT_PLACED = -1
val ORDER_STATUS_REQUESTED = 0
val ORDER_STATUS_CONFIRMED = 1
val ORDER_STATUS_COMPLETED = 4
val ORDER_STATUS_IN_PROGRESS = 3
val ORDER_STATUS_CANCELLED = 2

