package espl.apps.padosmart.utils

val GENDER_MALE = 0
val GENDER_FEMALE = 1
val GENDER_OTHERS = 2
val REQUEST_FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 34


val END_USER = 1
val SHOP_USER = 2
val SHOP_UNVERIFIED = 4
val SHOP_INIT_LOGIN = 5
val NEW_USER = 3
val AUTH_ACCESS_FAILED = 0

val PAYMENT_TYPE_CASH = 0
val PAYMENT_TYPE_CARD = 1
val PAYMENT_TYPE_MOBILE = 2

val QUERY_ARG_USER_ID = "customerID"
val QUERY_ARG_SHOP_ID = "shopPublicID"
val QUERY_ARG_ORDER_STATUS = "orderStatus"
val QUERY_ARG_CUSTOMER_ONLINE = "customerOnline"


val ORDER_STATUS_NOT_PLACED = -1
val ORDER_STATUS_REQUESTED = 0
val ORDER_STATUS_CONFIRMED = 1
val ORDER_STATUS_DELIVERED = 4
val ORDER_STATUS_IN_PROGRESS = 3
val ORDER_STATUS_CANCELLED = 2

